spring:
  docker:
    compose:
      enabled: false

  datasource:
    url: jdbc:postgresql://localhost:6432/fashionstore
    username: postgres
    password: postgres

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9999